# https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: capstone-app
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: vijaiananths/capstone
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  namespace: capstone-app
  labels:
    app: capstone
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: capstone
