# https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: vijaiananths/capstone
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 80